### ISSUE TITLE
Score not reseting to 0

### ISSUE THREAD

**Issue by Gluecke** [katerberg/numble#1]
When i started a new game, my score began counting from the end of my previous game.

How to repeat - 
Select normal game,
Submit callsign at end,
Click home,
Start normal game again,
Profit!

**Comment by katerberg** [comment]
Verified! Taking a look now.

**Comment by katerberg** [comment]
Thanks for the find @Shayngo!

Should be fixed now. I was previously resetting the game when leaving the results screen. It now resets before starting game to preventing forgetting to do so elsewhere.
